spring.application.name=payment-infra

server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payments}
spring.datasource.username=${DB_USERNAME:payment_user}
spring.datasource.password=${DB_PASSWORD:payment_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:payment-event-consumers}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always